---
- name: Palo Alto Playbook
  hosts: all
  connection: local
  vars:
    palo_provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  collections:
    - paloaltonetworks.panos

  tasks: 
    - name: Create SNMP v2 server
      panos_snmp_v2c_server:
        provider: '{{ palo_provider }}'
        snmp_profile: "{{ al_snmp_profile_name }}"
        name: '"{{ al_snmp_server_name }}"'
        manager: "{{ al_snmp_server_ip }}"
        community: "{{ al_snmp_community }}"
        commit: false

    - name: Commit 
      panos_commit_firewall:
        provider: '{{ palo_provider }}'     