
- hosts: all
  vars:
    configs_dir: "./labbackup/test/"
  tasks:

    - name: Get ansible date/time facts
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"

    - name: Store DTG as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

    - name: Create Directory {{hostvars.localhost.DTG}}
      file:
       path: ./{{configs_dir}}/{{hostvars.localhost.DTG}}
       state: directory

- name: Pull Configuration from Palo Alto Firewalls
  hosts: all
  tasks:

    - name: Generate API Key
      connection: local
      check_mode: no
      uri:
        validate_certs: no
        url: 'https://{{ansible_host}}/api/?type=keygen&user={{ansible_user}}&password={{ansible_password}}'
        return_content: yes
        method: GET
      register: key_string

    - name: Extract API Key from XML Output
      connection: local
      xml:
        xmlstring: '{{key_string.content}}'
        content: 'text'
        xpath: '/response/result/key'
      register: key_list

    - name: Backup configuration from PAN Equipment
      connection: local
      check_mode: no
      uri:
        validate_certs: no
        url: "https://{{ansible_host}}/api/?type=config&action=show&key={{key_list.matches[0].key}}"
        return_content: yes
        method: GET
      register: configuration_string
  
    - name: Remove XML Header and Save file in {{configs_dir}}
      connection: local
      check_mode: no
      copy:
        content: "{{configuration_string['content']  | regex_replace('<response.*<result>') | regex_replace('</result></response>')}}"
        dest: '{{configs_dir}}{{hostvars.localhost.DTG}}/{{inventory_hostname}}-{{hostvars.localhost.DTG}}-config.xml'
 