---
- hosts: all
  connection: local
  gather_facts: no
  vars:
    configs_dir: "/labbackup/"
  tasks:
    - name: Generate API Key
      
      check_mode: no
      uri:
        validate_certs: no
        url: 'https://{{ansible_host}}/api/?type=keygen&user={{ansible_user}}&password={{ansible_password}}'
        return_content: yes
        method: GET
      register: key_string

    - name: Extract API Key from XML Output       
      xml:
        xmlstring: '{{key_string.content}}'
        content: 'text'
        xpath: '/response/result/key'
      register: key_list

    - name: Backup configuration from PAN Equipment      
      check_mode: no
      uri:
        validate_certs: no
        url: "https://{{ansible_host}}/api/?type=config&action=show&key={{key_list.matches[0].key}}"
        return_content: yes
        method: GET
      register: configuration_string
  
    - name: Remove XML Header and Save file in {{configs_dir}}      
      check_mode: no
      copy:
        content: "{{configuration_string['content']  | regex_replace('<response.*<result>') | regex_replace('</result></response>')}}"
        dest: '{{configs_dir}}{{al_directory}}/{{hostname}}.txt'