---
- hosts: all
  connection: local
  gather_facts: no
  vars:
    configs_dir: "/labbackup/"
    palo_provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Push  configurations on each devices from the {{ configs_dir }} directory
      connection: local
      paloaltonetworks.panos.panos_import:
        provider: '{{ palo_provider }}'
        filename: '{{ configs_dir }}{{al_directory}}{{ al_backup_name }}'
        category: "configuration"
    - name: Load configurations on each devices
      paloaltonetworks.panos.panos_loadcfg:
        ip_address: "{{ ansible_host }}"
        password: "{{ ansible_password }}"
        file: '{{ al_backup_name }}'
        commit: 'true'