- name: Palo Alto Playbook
  hosts: all
  connection: local
  vars:
    palo_provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  collections:
    - paloaltonetworks.panos

  tasks: 
    - name: Set Server Profile TACACS
      paloaltonetworks.panos.panos_config_element:
        provider: '{{ palo_provider }}'
        xpath: "/config/shared/server-profile"
        element: |
          <tacplus>
            <entry name="SP-ALNET-TACACs">
              <server>
                <entry name="{{ al_tacacs_srv_name }}">
                  <secret>
                    {{ al_tacacs_key_enc }}
                  </secret>
                  <port>49</port>
                  <address>{{ al_tacacs_srv }}</address>
                </entry>
              </server>
              <protocol>CHAP</protocol>
            </entry>
          </tacplus>
    
    - name: Set Authentication Profile TACACS
      paloaltonetworks.panos.panos_config_element:
        provider: '{{ palo_provider }}'
        xpath: "/config/shared/authentication-profile"
        element: |
          <entry name="AP-ALNET-TACACs">
            <method>
              <tacplus>
                <server-profile>SP-ALNET-TACACs</server-profile>
              </tacplus>
            </method>
            <multi-factor-auth>
              <mfa-enable>no</mfa-enable>
            </multi-factor-auth>
            <allow-list>
              <member>all</member>
            </allow-list>
          </entry>

    - name: Configure Authentication Profile TACACS to be used on the Device
      paloaltonetworks.panos.panos_config_element:
        provider: '{{ palo_provider }}'
        xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system"
        element: |
          <authentication-profile>AP-ALNET-TACACs</authentication-profile>
    - name: FW Commit. Please be patient this will take a while.
      panos_commit_firewall:
        provider: '{{ palo_provider }}'        