- name: Palo Alto Playbook
  hosts: all
  connection: local
  vars:
    palo_provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  collections:
    - paloaltonetworks.panos

  tasks: 
    - name: Set Server Profile TACACS
      paloaltonetworks.panos.panos_config_element:
        provider: '{{ palo_provider }}'
        xpath: "/config/shared/server-profile"
        element: |
          <tacplus>
            <entry name="SP-ALNET-TACACs">
              <server>
                <entry name="{{ al_tacacs_srv_name }}">
                  <secret>
                    {{ al_tacacs_key }}
                  </secret>
                  <port>49</port>
                  <address>{{ al_tacacs_srv }}</address>
                </entry>
              </server>
              <protocol>CHAP</protocol>
            </entry>
          </tacplus>

#    - name: Commit 
#      panos_commit_firewall:
#        provider: '{{ palo_provider }}'        