- name: Palo Alto Playbook
  hosts: all
  connection: local
  vars:
    palo_provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  collections:
    - paloaltonetworks.panos

  tasks: 

    - name: Set Hostname 
      panos_mgtconfig: 
        provider: '{{ palo_provider }}'
        hostname: '{{ hostname }}'

    - name: Set DNS, NTP, Timez Zone and Panorama
      panos_mgtconfig: 
        provider: '{{ palo_provider }}'
        dns_server_primary: '{{ dns_primary_ip }}'
        ntp_server_primary: '{{ ntp_primary_ip }}'
        timezone: '{{ timezone_device }}'
#        dns_server_secondary: '{{ dns_secondary_ip }}'
#        panorama_primary: '{{ panorama_primary_ip }}'
#        panorama_secondary: '{{ panorama_secondary_ip }}'
        commit: false
    
#    - name: Set backup user account 
#      panos_administrator:
#        provider: '{{ palo_provider }}'
#        admin_username: '{{ adminusername }}'
#        admin_password: '{{ adminpassword }}'
#        superuser: true
#        commit: false 

    - name: Set Banner configuration
      panos_mgtconfig:
        provider: '{{ palo_provider }}'
        login_banner: |
            ###############################################################
            #                  This is a private server!                  #
            #       All connections are monitored and recorded.           #
            #  Disconnect IMMEDIATELY if you are not an authorized user!  #
            ###############################################################
        commit: false
    - name: Set SNMP device community and Info via API
      paloaltonetworks.panos.panos_config_element:
        provider: '{{ palo_provider }}'
        xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/snmp-setting"
        element: |
          <access-setting>
            <version>
              <v2c>
                <snmp-community-string>{{ al_snmp_community }}</snmp-community-string>
              </v2c>
            </version>
          </access-setting>
          <snmp-system>
            <location>{{ al_directory }}</location>
            <contact>Admin</contact>
          </snmp-system>

    - name: Commit 
      panos_commit_firewall:
        provider: '{{ palo_provider }}'        