- name: Palo Alto Playbook
  hosts: all
  connection: local
  vars:
    palo_provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  collections:
    - paloaltonetworks.panos

  tasks: 

    - name: Set Hostname 
      panos_mgtconfig: 
        provider: '{{ palo_provider }}'
        hostname: '{{ hostname }}'

    - name: Set DNS and Panorama
      panos_mgtconfig: 
        provider: '{{ palo_provider }}'
        dns_server_primary: '{{ dns_primary_ip }}'
#        dns_server_secondary: '{{ dns_secondary_ip }}'
#        panorama_primary: '{{ panorama_primary_ip }}'
#        panorama_secondary: '{{ panorama_secondary_ip }}'
        commit: false
    
#    - name: Set backup user account 
#      panos_administrator:
#        provider: '{{ palo_provider }}'
#        admin_username: '{{ adminusername }}'
#        admin_password: '{{ adminpassword }}'
#        superuser: true
#        commit: false 

    - name: Generic management settings
      panos_mgtconfig:
        provider: '{{ palo_provider }}'
        login_banner: |
            +-------------------------------------------------------------+
            |               !!! Authorized access only !!!                |
            |     You are authorized to use this System for approved      |
            |     business purposes only. Use for any other purpose       |
            |     is prohibited.                                          |
            |                                                             |
            |     All transactional records generated by using this       |
            |       System are the property of ABC and may be             |
            |        used by ABC for any purpose. Authorized              |
            |     and unauthorized activities will be monitored.          |
            +-------------------------------------------------------------+

            +-------------------------------------------------------------+
            |     Disconnect IMMEDIATELY if you are not authorized        |
            |     For access to this system contact:                      |
            |                                                             |
            |                 email@example.com                           |
            +-------------------------------------------------------------+
        commit: false

    - name: Commit 
      panos_commit_firewall:
        provider: '{{ palo_provider }}'        