---
collections:
  # Install a collection from Ansible Galaxy.
  - name: fortinet.fortios
    version: ">=2.1.6"
    source: https://galaxy.ansible.com
  - name: paloaltonetworks.panos
    source: https://galaxy.ansible.com
  - name: ansible.netcommon
    source: https://galaxy.ansible.com
  - name: cisco.ios
    source: https://galaxy.ansible.com