---
- hosts: all
  collections:
   - fortinet.fortios
  connection: httpapi
  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      vdom:  "{{ vdom }}"
      system_global:
        admintimeout: "23"
        hostname: "FortiGate02"
