---
- hosts: all
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
  tasks:
  - name: Backup a virtual domain.
    fortios_monitor_fact:
       selector: 'system_config_backup'
       vdom: 'root'
       params:
           scope: 'global'
    register: backupinfo

  - name: Save pre backup
    copy:
       src: '/tmp/{{ al_directory }}{{ al_hostname }}.backup'
       dest: '/tmp/{{ al_directory }}{{ al_hostname }}-001.backup'
  
  - name: Save the backup information.
    copy:
       content: '{{ backupinfo.meta.raw }}'
       dest: '/tmp/{{ al_directory }}{{ al_hostname }}.backup'
