---
- hosts: all
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
  tasks:
  - name: Restore from file.
    fortios_monitor:
      selector: 'restore.system.config'
      vdom: 'root'
      params:
          scope: 'global'
          source: 'upload'
          vdom: 'root'
          file_content: "{{ lookup( 'file', '/labbackup/{{ al_directory }}{{ al_backup_name }}') | string | b64encode }}"