---
- hosts: all
  collections:
   - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 80
  tasks:
    - name: Define SNMP Community
      fortios_system_snmp_community:
        state: "present"
        system_snmp_community:
          name: "{{ al_snmp_community }}"
          status: enable
          hosts:
          -
              id: "1"
              ip: "10.100.140.32"
              source_ip: "{{ ansible_host }}"
          id: "1"
    - name: Enable SNMP SYSINFO
      fortios_system_snmp_sysinfo:
        system_snmp_sysinfo:
          status: enable
          description: TLABTEST