---
- hosts: all
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      system_global:
        admin_host: "myhostname"
