- hosts: all
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no # change on PRO Env
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 80 # change on PRO Env
  tasks:
  - name: Configure TACACS+ Server entries.
    fortios_user_tacacsplus:
      vdom:  "{{ vdom }}"
      state: "present"
      user_tacacsplus:
        authen_type: "chap"  # change on PRO Env
        authorization: "enable"
        interface: "port4"
        interface_select_method: "auto"
        key: "{{ al_tacacs_key }}"
        name: "ALNet-TACACS"
        port: "49"
        server: "{{ al_tacacs_srv }}"
        source_ip: "{{ ansible_host }}"
  - name: Configure TACACS+ User Group
    fortios_user_group:
      vdom:  "{{ vdom }}"
      state: "present"
      user_group:
        group_type: firewall
        name: "T-Group"
        member:
          - 
              name: "ALNet-TACACS"
  - name: Configure Admin user for TACACS+
    fortios_system_admin:
      vdom:  "{{ vdom }}"
      state: "present"
      system_admin:
        name: "ALNet_T"
        accprofile: "prof_admin"
        remote_group: "T-Group"