---
- hosts: all
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_network_os: fortinet.fortios.fortios
     ansible_httpapi_use_ssl: yes
     ansible_httpapi_validate_certs: no
     ansible_httpapi_port: 443
  tasks:
  - name: Backup a virtual domain.
    fortios_monitor_fact:
       selector: 'system_config_backup'
       vdom: 'root'
       params:
           scope: 'global'
    register: backupinfo
  
  - name: Save the backup information.
    copy:
       content: '{{ backupinfo.meta.raw }}'
       dest: '/tmp/local.backup'
