---
- hosts: all
  collections:
   - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 80
  tasks:
    - name: Define SNMP Community
      fortios_switch_controller_snmp_community:
        name: "{{ al_snmp_community }}"
        status: enable
        state: absent
        system_snmp_community:
          hosts:
          -
              id: "1"
              host_type: "any"
              ha_direct: "enable"
              ip: "10.100.140.32"
              source_ip: "{{ ansible_host }}"
    - name: Enable SNMP SYSINFO
      fortios_switch_controller_snmp_sysinfo:
        status: enable
        description: TLABTEST