---
- hosts: all
  collections:
   - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 80
  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      vdom:  "{{ vdom }}"
      system_global:
        admintimeout: "480"
        hostname: "LAB-Main-001"
  - name: Configure IPv4/IPv6 policies.
    fortios_firewall_policy:
      vdom:  "{{ vdom }}"
      state: "present"  
      firewall_policy:
        action: "accept"
        policyid: "1"
        dstaddr:
          - name: all
        srcaddr:
          - name: all
        dstintf:
          - name: any
        srcintf:
          - name: any
        service:
          - name: ALL