---
- hosts: all
  tasks:
    - name: send configuration
      ansible.netcommon.telnet:
        login_prompt: 'FortiGate-VM64-KVM login: '
        prompts:
        - '[>#]'
        command:
        - show sys int
        - show sys zone
