---
- hosts: all
  connection: local
  gather_facts: false
#  collections:
#    - ansible.netcommon.telnet
  tasks:
    - name: send configuration
      ansible.netcommon.telnet:
        send_newline: true
        port: "{{ TPORT }}"
        login_prompt: '[login: ]'
        password_prompt: "Password: "
        prompts:
        - '[>#]'        
        command:
        - config system int
        - edit port3
        - set mode static
        - set ip "{{ MGMTIP }}"/24
        - end
