---
- hosts: all
  connection: local
  gather_facts: true
  collections:
    - ansible.netcommon
  tasks:
    - name: send configuration
      telnet:
        login_prompt: 'FortiGate-VM64-KVM login: '
        prompts:
        - '[>#]'        
        command:
        - show sys int
        - show sys zone
