---
- hosts: all
  tasks:
    - name: send configuration
      ansible.netcommon.telnet:
        login_prompt: ': '
        prompts:
        - '[>#]'        
        command:
        - show sys int
        - show sys zone
