---
- hosts: all
  connection: local
  gather_facts: false
#  collections:
#    - ansible.netcommon.telnet
  tasks:
    - name: send configuration
      ansible.netcommon.telnet:
        port: "{{ TPORT }}"
        login_prompt: '[login: ]'
        password_prompt: "Password: "
        prompts:
        - '[>#]'        
        command:
        - config system global
        - set hostname LAB-TEST-Auto2
        - end
