---
- hosts: all
  connection: local
  gather_facts: false
#  collections:
#    - ansible.netcommon.telnet
  tasks:
    - name: send configuration
      ansible.netcommon.telnet:
        crlf: true
        port: "{{ TPORT }}"
        login_prompt: '[login: ]'
        password_prompt: "Password: "
        prompts:
        - '[>#]'        
        command:
        - config system int
        - edit port4
        - set mode static
        - set ip "{{ MGMTIP }}"/24
        - end
        - config router static
        - edit 1
        - set gateway {{ MGMTIP }}
        - set device "port4"
        - end
        - config sys global
        - set hostname {{ al_host }}
        - end
