---
- hosts: all
  connection: local
  gather_facts: false
  collections:
    - ansible.netcommon
  tasks:
    - name: send configuration
      telnet:
        login_prompt: 'FortiGate-VM64-KVM login: '
        prompts:
        - '[>#]'        
        command:
        - config system global
        - set hostname LAB-TEST-Auto2
        - end
        - exit
