---
- hosts: all

  become: true
  tasks:
    - name: "Update System"
      apt:
        update_cache: yes
        state: present
        name: "rsyslog"
    
    - name: "Append PROMPT_COMMAND Environment Variable"
      lineinfile:
        path: /etc/bash.bashrc
        regexp: "^export PROMPT_COMMAND=.*$"
        line: "export PROMPT_COMMAND='RETRN_VAL=$?; if [ -f /tmp/lastoutput.tmp ]; then LAST_OUTPUT=$(cat /tmp/lastoutput.tmp); rm /tmp/lastoutput.tmp; fi; logger -S 10000 -p local6.debug \"{\\\"user\\\": \\\"$(whoami)\\\", \\\"path\\\": \\\"$(pwd)\\\", \\\"pid\\\": \\\"$$\\\", \\\"b64_command\\\": \\\"$(history 1 | sed -r \"s/^\\s*[0-9]+\\s*//\" | base64 -w0 )\\\", \\\"status\\\": \\\"$RETRN_VAL\\\", \\\"b64_output\\\": \\\"$LAST_OUTPUT\\\"}\"; unset LAST_OUTPUT; '"
    
    - name: "Append logoutput Helper Command to Bash Profile"
      lineinfile:
        path: /etc/bash.bashrc
        line: 'logoutput() { output=$(while read input; do echo "$input"; done < "${1:-/dev/stdin}"); echo -e "$output\n"; echo -e "$output" | head -c 10000 | base64 -w0 > /tmp/lastoutput.tmp; return $?; }'
        