---
- hosts: all
  gather_facts: no

  tasks:

  - name: CONFIGURE BANNER ON CISCO DEVICES
    ios_banner:
      banner: login
      text: "{{ lookup('file', './vars/banner.cfg') }}"
      state: present

  - name: DELETE INCOMING BANNER ON CISCO DEVICES
    ios_banner:
      banner: incoming
      state: absent

  - name: DELETE EXEC BANNER ON CISCO DEVICES
    ios_banner:
      banner: exec
      state: absent