---
- hosts: all
  gather_facts: no

  tasks:

  - name: CONFIGURE BANNER ON CISCO DEVICES
    ios_banner:
      banner: exec
      text: "{{ lookup('file', './vars/banner.cfg') }}"
      state: present

  - name: DELETE INCOMING BANNER ON CISCO DEVICES
    ios_banner:
      banner: incoming
      text: ""
      state: present

  - name: DELETE LOGIN BANNER ON CISCO DEVICES
    ios_banner:
      banner: login
      text: ""
      state: present