---
- name: Backup Cisco Router or Switch
  hosts: Cisco
  connection: network_cli
  gather_facts: false
  vars:
    configs_dir: "/labbackup/"
  tasks:
    - name: Access ansible net hostname
      ios_facts:
        gather_subset: all
    - name: Get current date
      local_action: command date +%Y-%m-%d
      register: date
    - name: Get current time
      local_action: command date +%H_%M
      register: time
    - name: Get running-config and save it
      ios_config:
       backup: yes
       backup_options:
         #ansible_host = getting device IP, ansible_net_hostname = getting device hostname
         #filename: "{{ date.stdout }}_{{al_hostname}}_{{ ansible_host }}.cfg"
         filename: "{{ date.stdout }}_{{al_hostname}}.cfg"
         dir_path: "/{{configs_dir}}{{al_directory}}{{al_hostname}}"
    - name: Tasks done
      debug: msg="All tasks has been done on {{ date.stdout }} at {{ time.stdout }}."