---
- hosts: all
  gather_facts: false

  tasks:
    
    - name: get interface status
      ios_command:
        commands: 
          - show ip int bri
      register: output
      
    - debug:
        msg: "{{ output }}"