---
- hosts: all
  gather_facts: no
  tasks:
    - name: Configure TACACS+
      ios_config:
        lines:
          - tacacs server {{ al_tacacs_profile }}
          - address ipv4 {{ al_tacacs_srv }}
          - key {{ al_tacacs_key }}
          - aaa authentication login {{ al_tacacs_profile }} local group tacacs+
          - line vty 0 4
          - login authentication {{ al_tacacs_profile }}
          #- aaa authentication enable default group TACACS-SERVER-GROUP enable
          #- aaa authorization exec default group TACACS-SERVER-GROUP local
          #- aaa accounting exec default start-stop group TACACS-SERVER-GROUP
          #- aaa accounting commands 15 default start-stop group TACACS-SERVER-GROUP
