---
- hosts: all
  gather_facts: yes
  connection: network_cli
  vars:
    configs_dir: "/labbackup/"
  tasks:
  - name: Gather legacy and resource facts # Must, using legacy!!
    cisco.ios.ios_facts:
      gather_subset: all
  - name: Creates directory
    ansible.builtin.file:
      path: "/{{configs_dir}}{{al_directory}}{{al_hostname}}/json"
      state: directory
  - name: Register Timestamp
    shell: date +%Y%m%d%H%M%S
    register: timestamp
  - name: GATHER FACTS TO JSON
    register: iosfacts_out
    ios_facts:

  - copy: content="{{ iosfacts_out | to_nice_json }}" dest="/{{configs_dir}}{{al_directory}}{{al_hostname}}/json/{{al_hostname}}_{{ timestamp.stdout }}_iosfacts.json"