---
- hosts: all
  gather_facts: no

  tasks:

  - name: CONFIGURE BANNER ON CISCO DEVICES
    ios_banner:
      banner: incoming
      text: "{{ lookup('file', './vars/banner.cfg') }}"
      state: present

  - name: SHOW RUN | BEG BANNER 
    ios_command:
      commands:
        - show run | beg banner
    register: banner

  - debug: var=banner.stdout_lines