---
- hosts: all
  gather_facts: no
  vars:
    tacacs_servers: [10.100.140.34]
    tacacs_server_key: "Pal0Alt0!"
    tacacs_server_timeout: 5
    #tacacs_source_interface:
  tasks:
    - name: Configure TACACS+
      ios_config:
        lines:
          - tacacs server ALNET-T01
          - address ipv4 10.100.140.32
          - key Pal0Alt0!
          - aaa group server tacacs+ TACACS-SERVER-GROUP
          - server name ALNET-T01
          - ip tacacs source-interface GigabitEthernet0/7.76
          - aaa authentication login default group TACACS-SERVER-GROUP local  
          - aaa authentication enable default group TACACS-SERVER-GROUP enable
          - aaa authorization exec default group TACACS-SERVER-GROUP local
          - aaa accounting exec default start-stop group TACACS-SERVER-GROUP
          - aaa accounting commands 15 default start-stop group TACACS-SERVER-GROUP
