---
- hosts: all
  gather_facts: no

  tasks:
  - name: IOS >> Save Configuration to NVRAM
    ios_config:
      save_when: always
    register: output

  - name: DEBUG >> output
    debug:
      msg: "{{ output }}"