---
- hosts: all
  gather_facts: no
  tasks:
 
  - name: SET COMMUNITY STRING 
    ios_config:
      lines:
        - snmp-server community {{ al_snmp_community }} RO
  #- name: TRAP-SOURCE {{ al_snmp_source }}
  #  ios_config:
  #    lines:
  #       - snmp-server trap-source {{ al_snmp_source }}

  - name: SET CONTACT INFO 
    ios_config:
      lines:
        - snmp-server contact {{ al_snmp_contact }}


  #- name: SET SNMP SERVER ADDRESS to send Notificactions
  #  ios_config:
  #    lines:
  #      - snmp-server host 10.100.140.32 version 2c al_network_ro
  #      - snmp-server enable traps

  #- name: ENABLE TRAPS 
  #  ios_config:
  #    lines:
  #      - snmp-server enable traps ospf state-change
  #      - snmp-server enable traps ospf errors
  #      - snmp-server enable traps ospf retransmit
  #      - snmp-server enable traps ospf lsa
  #      - snmp-server enable traps ospf cisco-specific errors
  #      - snmp-server enable traps ospf cisco-specific retransmit
  #      - snmp-server enable traps ospf cisco-specific lsa