---
- hosts: all
  gather_facts: no
  tasks:
    - name: Configure TACACS+ AAA (conditional)
      ios_config:
        lines: "{{ item }}"
      with_items:
        - aaa authentication login default local group tacacs+
        #- aaa authentication enable default group tacacs+ enable # Not needed so far, don't use enable password
        - aaa authorization commands 15 default local group tacacs+
        #- aaa accounting exec default stop-only group tacacs+
        #- aaa accounting commands 15 default stop-only group tacacs+
        #- aaa accounting network default stop-only group tacacs+
      when: al_tacacs_srv is defined

    - name: Configure TACACS+ Server & Key
      ios_config:
        lines: "tacacs-server host {{ al_tacacs_srv }} key {{al_tacacs_key}}"
      when: al_tacacs_srv is defined and al_tacacs_key is defined

    - name: Configure TACACS+ timeout
      ios_config:
        lines: "tacacs-server timeout {{al_server_timeout}}"
      when: al_tacacs_srv is defined and al_server_timeout is defined

    - name: Configure TACACS+ source interface
      ios_config:
        lines: "ip tacacs source-interface {{al_source_interface}}"
      when: al_tacacs_srv is defined and al_source_interface is defined
