---
- name: Backup Cisco Router or Switch
  hosts: Cisco
  connection: network_cli
  gather_facts: false
  host_key_checking: false
  vars:
    configs_dir: "/labbackup/"
  tasks:
    - name: Access ansible net hostname
      ios_facts:
        gather_subset: all
    - name: Get current date
      local_action: command date +%Y-%b-%d
      register: date
    - name: Get current time
      local_action: command date +%H:%M
      register: time
    - name: Get running-config and save it
      ios_config:
       backup: yes
       backup_options:
         #ansible_host = getting device IP, ansible_net_hostname = getting device hostname
         filename: "{{al_hostname}}_{{ ansible_host }}.cfg"
         dir_path: /{{configs_dir}}{{al_directory}}{{ date.stdout }}_at_{{ time.stdout }}
    - name: Tasks done
      debug: msg="All tasks has been done on {{ date.stdout }} at {{ time.stdout }}."