---
- hosts: all
  gather_facts: false

  tasks:
    
    - name: get interface status
      ios_command:
        commands: 
          - show ip int bri
      register: output
      
    - debug:
        msg: "{{ item.interface }}"
      when: item.state == "connected"
      loop: "{{ output.stdout.0.TABLE_interface.ROW_interface }}"